var express = require('express');
var router = express.Router();

//Glossary Table Entries
const Glossary =[

  { 'id': 1, 'term': 'DevOps', 'description': 'DevOps is a combination of the two words, "Development" and "Operations"[3] ', 'references': '[3] M. Krief, Learning DevOps -Second Edition, S. Iqbal, ed., Second Edition ed. Birmingham, UK: Packt Publishing Ltd, 2022, p. 560. [Online]. Available: https://learning.oreilly.com/library/view/learning-devops/9781801818964/. Accessed on: 21/07/2023.'}, 
  { 'id': 2, 'term': 'Microservices', 'description': 'A Microservice is a a small independant software process which can be updated independantly from other processes. [1]  ', 'references': '[1] A. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform, Shelter Island, NY: Manning Publications, 2021. [Online]. Available: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212. Accessed on: 21/07/2023.'},
  { 'id': 3, 'term': 'Docker Compose', 'description': 'A tool created by the people who developed Docker. It builds on top of Docker to assist managing multi-container applications. Simply put it uses a script file that assists in the creation of an application from a collection of Docker files. ', 'references': '[2] A. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform, Shelter Island, NY: Manning Publications, 2021. [Online]. Available: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212. Accessed on: 21/07/2023.'},
  { 'id': 4, 'term': 'Kubernetes', 'description': 'Kubernetes is a container orchestrator tool. It managers containerised applications from container engines like Docker and assists with the deployment and management of containers.[2]', 'references': '[2] N. Kebbani, P. Tylenda, and R. McKendrick, The Kubernetes bible : learn how to deploy and manage Kubernetes across every cloud platform, Birmingham: Packt Publishing, 2022, p. 680. [Online]. Available: https://learning.oreilly.com/library/view/the-kubernetes-bible/9781838827694/.'}, 
  { 'id': 5, 'term': 'Terraform', 'description': 'Terraform is an Infrastrucure as code tool that enables the scripting of infrastrucure deployment. Similar in purpose to Docker compose but can also be used along side of.[1] ', 'references': '[1] A. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform, Shelter Island, NY: Manning Publications, 2021. [Online]. Available: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212. Accessed on: 21/07/2023.'}, 
  { 'id': 6, 'term': 'IaC', 'description': 'Infrastrucure as Code or IaC is the process of automating the creation of Infrastructure through code files as opposed to manually creating and allocating them through other means such as a GUI. Both Docker Compose and Terraform are an example of IAC. [1]', 'references': '[1] A. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform, Shelter Island, NY: Manning Publications, 2021. [Online]. Available: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212. Accessed on: 21/07/2023.'}, 
  { 'id': 7, 'term': 'Agile', 'description': 'Agile is way of doing software development. It is a set of methodologies to assist software development teams work more collaboratively together and is designed to streamline and optimise Software Development. [5] ', 'references': '[5] A. a. G. Stellman, Jennifer, Learning Agile, M. Treseler, ed., First Edition ed.: O’Reilly Media, Inc, 2014. [Online]. Available: https://learning.oreilly.com/library/view/learning-agile/9781449363819/. Accessed on: 22/07/2023.'}, 
  { 'id': 8, 'term': 'Git', 'description': 'Git is a version control system or Source Code Managment (SCM) primarily used for code and documents.  It allows teams to collaborate on code and it can also run checks on the code to ensure compliance with various standards if required.[4]', 'references': '[4] A. Skoulikari, Learning Git, Sebastopol, CA: O’Reilly Media, Inc, 2023, p. 317. [Online]. Available: https://learning.oreilly.com/library/view/learning-git/9781098133900/. Accessed on: 23/07/2023.'}, 
  { 'id': 9, 'term': 'DevSecOps', 'description': 'DevSecOPs is the inclusion of Security in the DevOps process. It puts security at the forefront by assuming a security focus as early as possible in the DevOps process.  This means involving a security team in process to create a DevSecOps culture. [3] ', 'references': '[3] M. Krief, Learning DevOps -Second Edition, S. Iqbal, ed., Second Edition ed. Birmingham, UK: Packt Publishing Ltd, 2022, p. 560. [Online]. Available: https://learning.oreilly.com/library/view/learning-devops/9781801818964/. Accessed on: 21/07/2023.'}, 
  { 'id': 10, 'term': 'CI', 'description': 'Continuous Intergration or CI as it is known is where a software development team intergrate their work on a frequent basis.  These intergrations are checked by an automatic process to determine the completeness of the code. ', 'references': '[3] M. Krief, Learning DevOps -Second Edition, S. Iqbal, ed., Second Edition ed. Birmingham, UK: Packt Publishing Ltd, 2022, p. 560. [Online]. Available: https://learning.oreilly.com/library/view/learning-devops/9781801818964/. Accessed on: 21/07/2023.'} 

];


/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary', subtitle: 'My collection of DevOps related terms and meanings', theadid: 'ID#', theadterm: 'Term', theaddesc: 'Description', theadref: 'References', Glossary:Glossary });
});

module.exports = router;
