var express = require('express');
var router = express.Router();

//Glossary Table Entries
const Glossary =[

  { 'id': 1, 'term': 'DevOps', 'description': 'DevOps is a combination of the two words, "Development" and "Operations"[3] ', 'references': '[3] M. Krief, Learning DevOps -Second Edition, S. Iqbal, ed., Second Edition ed. Birmingham, UK: Packt Publishing Ltd, 2022, p. 560. [Online]. Available: https://learning.oreilly.com/library/view/learning-devops/9781801818964/. Accessed on: 21/07/2023.'}, 
  { 'id': 2, 'term': 'Microservices', 'description': 'A Microservice is a a small independant software process which can be updated independantly from other processes. [1]  ', 'references': '[1] A. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform, Shelter Island, NY: Manning Publications, 2021. [Online]. Available: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212. Accessed on: 21/07/2023.'},
  { 'id': 3, 'term': 'Docker Compose', 'description': 'A tool created by the people who developed Docker. It builds on top of Docker to assist managing multi-container applications. Simply put it uses a script file that assists in the creation of an application from a collection of Docker files. ', 'references': '[2] A. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform, Shelter Island, NY: Manning Publications, 2021. [Online]. Available: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212. Accessed on: 21/07/2023.'},
  { 'id': 4, 'term': 'Kubernetes', 'description': 'Kubernetes is a container orchestrator tool. It managers containerised applications from container engines like Docker and assists with the deployment and management of containers.[2]', 'references': '[2] N. Kebbani, P. Tylenda, and R. McKendrick, The Kubernetes bible : learn how to deploy and manage Kubernetes across every cloud platform, Birmingham: Packt Publishing, 2022, p. 680. [Online]. Available: https://learning.oreilly.com/library/view/the-kubernetes-bible/9781838827694/.'}, 
  { 'id': 5, 'term': 'Terraform', 'description': 'Terraform is an Infrastrucure as code tool that enables the scripting of infrastrucure deployment. Similar in purpose to Docker compose but can also be used along side of.[1] ', 'references': '[1] A. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform, Shelter Island, NY: Manning Publications, 2021. [Online]. Available: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212. Accessed on: 21/07/2023.'}, 
  { 'id': 6, 'term': 'IaC', 'description': 'Infrastrucure as Code or IaC is the process of automating the creation of Infrastructure through code files as opposed to manually creating and allocating them through other means such as a GUI. Both Docker Compose and Terraform are an example of IAC. [1]', 'references': '[1] A. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform, Shelter Island, NY: Manning Publications, 2021. [Online]. Available: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212. Accessed on: 21/07/2023.'}, 
  { 'id': 7, 'term': 'Agile', 'description': 'Agile is way of doing software development. It is a set of methodologies to assist software development teams work more collaboratively together and is designed to streamline and optimise Software Development. [5] ', 'references': '[5] A. a. G. Stellman, Jennifer, Learning Agile, M. Treseler, ed., First Edition ed.: O’Reilly Media, Inc, 2014. [Online]. Available: https://learning.oreilly.com/library/view/learning-agile/9781449363819/. Accessed on: 22/07/2023.'}, 
  { 'id': 8, 'term': 'Git', 'description': 'Git is a version control system or Source Code Managment (SCM) primarily used for code and documents.  It allows teams to collaborate on code and it can also run checks on the code to ensure compliance with various standards if required.[4]', 'references': '[4] A. Skoulikari, Learning Git, Sebastopol, CA: O’Reilly Media, Inc, 2023, p. 317. [Online]. Available: https://learning.oreilly.com/library/view/learning-git/9781098133900/. Accessed on: 23/07/2023.'}, 
  { 'id': 9, 'term': 'DevSecOps', 'description': 'DevSecOPs is the inclusion of Security in the DevOps process. It puts security at the forefront by assuming a security focus as early as possible in the DevOps process.  This means involving a security team in process to create a DevSecOps culture. [3] ', 'references': '[3] M. Krief, Learning DevOps -Second Edition, S. Iqbal, ed., Second Edition ed. Birmingham, UK: Packt Publishing Ltd, 2022, p. 560. [Online]. Available: https://learning.oreilly.com/library/view/learning-devops/9781801818964/. Accessed on: 21/07/2023.'}, 
  { 'id': 10, 'term': 'CI', 'description': 'Continuous Intergration or CI as it is known is where a software development team intergrate their work on a frequent basis.  These intergrations are checked by an automatic process to determine the completeness of the code. ', 'references': '[3] M. Krief, Learning DevOps -Second Edition, S. Iqbal, ed., Second Edition ed. Birmingham, UK: Packt Publishing Ltd, 2022, p. 560. [Online]. Available: https://learning.oreilly.com/library/view/learning-devops/9781801818964/. Accessed on: 21/07/2023.'}, 
  { 'id': 11, 'term': 'CD', 'description': 'Continuous Delivery is the automated delivery of code once complete.  This is not to be confused with Continuous Deployment which is a phsase  of Continous Delivery.[6] ', 'references': '[6] Synopsys, “Why is CI/CD important?,” Synopsys, 2023. [Online]. Available: https://www.synopsys.com/glossary/what-is-cicd.html#:~:text=Continuous%20delivery%20(CD)%20is%20the,next%20step%20of%20continuous%20delivery.. [Accessed 2 8 2023].'}, 
  { 'id': 12, 'term': 'QA', 'description': 'Quality Assurance(QA) is part of the software development process and involved testing and checking the product to ensure that it complies with requirements.[7] ', 'references': '[7] M. Raza, “Quality Assurance (QA) in Software Testing: QA Views & Best Practices,” BMC, 16 4 2021. [Online]. Available: https://www.bmc.com/blogs/quality-assurance-software-testing/. [Accessed 2 8 2023].'}, 
  { 'id': 13, 'term': 'Splunk', 'description': 'Splunk is a data and analysis tool that allows you to search and analyse data from any system that it can interact with.[8] ', 'references': '[8] K. Chrissy, “What Splunk Does,” Splunk, 18 11 2022. [Online]. Available: https://www.splunk.com/en_us/blog/learn/what-splunk-does.html. [Accessed 6 8 2023].'}, 
  { 'id': 14, 'term': 'Regression Testing', 'description': 'Regression Testing is a form of software testing that is conducted after updating some code to ensure that the update has not introduced any new bugs.[9] ', 'references': '[9] Katalon, “What is Regression Testing? Definition, Tools and Examples,” Katalon, 2023. [Online]. Available: https://katalon.com/resources-center/blog/regression-testing. [Accessed 6 8 2023]. '}, 
  { 'id': 15, 'term': 'DevOps Cycle', 'description': 'The DevOps lifecycle is the lifecycle of the DevOps development process. It has seven stages: Plan, Create, Verify, Preprod, Release, Configure and Monitor.[10] ', 'references': '[10] Mulder, J. (2021). Enterprise DevOps for Architects (S. Iqbal, R. Dias, & A. Varma, Eds.). Packt Publishing Ltd. '}, 
  { 'id': 16, 'term': 'Jira Align', 'description': 'Jira Align, formally known as AgileCraft is a planning tool used in the Plan stage of the DevOps cycle to assist in the use of Agile in the Enterprise [11] ', 'references': '[11] Cprime, “What is Jira Align?,” Cprime, 2023. [Online]. Available: https://www.cprime.com/what-is-jira-align/#:~:text=Jira%20Align%20helps%20software%20organizations,customer%20outcomes%20at%20enterprise%20scale.. [Accessed 6 8 2023].'}, 
  { 'id': 17, 'term': 'Subversion', 'description': 'Known as Apache Subversion or SVN this is a software versioning and revision control system created in 2004.[11] ', 'references': '[11] Apache, “Apache® Subversion®,” Apache, 2023. [Online]. Available: https://subversion.apache.org/. [Accessed 6 8 2023].'}, 
  { 'id': 18, 'term': 'Extreme Programming', 'description': 'Extreme Programming is an Agile Software development model which uses approaches such as Dynamic System Development and Adaptive software Development which are derived from Rapid Application Development system developmd by Jum Highsmith involkving a repearing series of development cycles."[10] ', 'references': '[10] Mulder, J. (2021). Enterprise DevOps for Architects (S. Iqbal, R. Dias, & A. Varma, Eds.). Packt Publishing Ltd.'}, 
  { 'id': 19, 'term': 'Scrum', 'description': 'Scrum is an Agile Software development model in which small teams work in a "Scrum" to develop software, often delivered in  "sprints".[10] ', 'references': '[10] Mulder, J. (2021). Enterprise DevOps for Architects (S. Iqbal, R. Dias, & A. Varma, Eds.). Packt Publishing Ltd.'}, 
  { 'id': 20, 'term': 'Unified Process', 'description': 'Unified Process is an Agile software development model based on the Rational Unified Process (RUP) software development process from IBM. It uses four processes and is business model based."[10] ', 'references': '[10] Mulder, J. (2021). Enterprise DevOps for Architects (S. Iqbal, R. Dias, & A. Varma, Eds.). Packt Publishing Ltd.'}, 
];


/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary', subtitle: 'My collection of DevOps related terms and meanings', theadid: 'ID#', theadterm: 'Term', theaddesc: 'Description', theadref: 'References', Glossary:Glossary });
});

module.exports = router;
